### PR TITLE
restart the agent if its config files change

### PR DESCRIPTION
**Pull request by redterror**
Subject says it all.

If this looks good, can you please crank the version after this so I can drop the override in my berksfile?  :)

### CODE REVIEW

**Comment by imron** [comment]
The agent should automatically reload its configuration if any of the configuration files change.

In that case, running chef-client -r 'recipe[scalyr_agent::configure]' should be sufficient for the agent to pick up the configuration changes (though depending on how the agent is configured this could take 30 seconds or so).

Have you noticed that this is not happening, or are you looking for a hard manual restart?

If the former that's a bug we should fix, if the latter, some users might want to avoid a restart so as not to have any downtime of the agent and would it possible to put whether or not to restart the agent behind a config option?

Maybe something like default['scalyr_agent']['autorestart'] = false  in attributes/default.rb

And then having the restart code checking for the existence of that flag and only restarting if true.

**Comment by redterror** [comment]
> The agent should automatically reload its configuration if any of the configuration files change.

Ah, I wasn't aware.  In that case, I would say perhaps add some doc notes to the readme that the restarts are unnecessary.

**Comment by imron** [comment]
No worries.  It's mentioned in the [main documentation](https://www.scalyr.com/help/scalyr-agent#modularConfig) for the agent, but I'll update the README for our chef cookbook to mention it also (and bump the version number while I'm at it for the previous changes you made).

**Comment by imron** [comment]
Ok, that's done now and I've also pushed the changes to the chef supermarket.

**Comment by redterror** [comment]
Turns out I *am* having the issue - my wrapper cookbook updated `/etc/scalyr-agent-2/agent.d/logs.json` last night and I'm not seeing the log appear in the UI.  I'm guessing this isn't the best place to report that - what's the best path forward?

**Comment by czerwingithub** [comment]
Hi Dan -

Let's move this to support@scalyr.com, cc czerwin@scalyr.com (me)  and
we'll take it from there.  Can you send an email to those addresses and
we'll kick off diagnosing the problem.

thanks,
Steve

**Pull request closed without merging**
