### PR TITLE
Pass package to apt_package individually

### PR DESCRIPTION
**Pull request by smo921**
Older versions of chef don't support passing array's to resources such as `apt_package`.  Iterating the array of packages makes this compatible with older versions of the chef client.

### CODE REVIEW

**Comment by imron** [comment]
Hi Stephen, thanks for submitting this.  The code looks good, can you also bump the version number in metadata.rb to 0.1.4 then I'll merge this in.

**Comment by imron** [comment]
@jmorascalyr can you push this latest version to the chef supermarket?

**Comment by jmorascalyr** [comment]
@imron sure no problem. Should have it pushed by tomorrow EOD.

**Comment by jmorascalyr** [comment]
@imron Version 0.1.4 successfully pushed to the Chef Supermarket.

**Pull request merged**
